# ----------------------------------------------------------------------------
# GML 3.2
# ----------------------------------------------------------------------------
- name: clone testsuite form GML-3.2
  git:
    repo: https://github.com/opengeospatial/ets-gml32
    dest: '/home/{{ user }}/ets-gml32'
    version: '{{ ets_gml32_version }}'
  become: yes
  become_user: '{{ user }}'
  register: pull_gml32

- name: build ets-gml32
  command: mvn install
  args:
    chdir: /home/{{ user }}/ets-gml32
  become: yes
  become_user: '{{ user }}'
  when: pull_gml32.changed

- name: install ets-gml32 scripts
  unarchive:
    src: /home/{{ user }}/ets-gml32/target/ets-gml32-{{ ets_gml32_version }}-ctl.zip
    dest: /srv/teamengine/scripts
    remote_src: true

- name: install ets-gml32 resources lib
  unarchive:
    src: /home/{{ user }}/ets-gml32/target/ets-gml32-{{ ets_gml32_version }}-deps.zip
    dest: /srv/teamengine/resources/lib
    remote_src: true

# ----------------------------------------------------------------------------
# WMS 1.1.0
# ----------------------------------------------------------------------------
- name: clone testsuite for WMS-1.1.0
  git:
    repo: https://github.com/opengeospatial/ets-wms11
    dest: '/home/{{ user }}/ets-wms11'
    version: '{{ ets_wms11_version }}'
  become: yes
  become_user: '{{ user }}'
  register: pull_wms110

- name: build ets-wms11
  command: mvn install
  args:
    chdir: /home/{{ user }}/ets-wms11
  become: yes
  become_user: '{{ user }}'
  when: pull_wms110.changed

- name: install ets-wms11 scripts
  unarchive:
    src: /home/{{ user }}/ets-wms11/target/ets-wms11-{{ ets_wms11_version }}-ctl.zip
    dest: /srv/teamengine/scripts
    remote_src: true

- name: install ets-wms11 resources lib
  unarchive:
    src: /home/{{ user }}/ets-wms11/target/{{ item }}
    dest: /srv/teamengine/resources/lib
    remote_src: true
  with_items:
    - ets-wms11-{{ ets_wms11_version }}-deps.zip

- name: install ets-wms11 site jar
  copy:
    src: /home/{{ user }}/ets-wms11/target/{{ item }}
    dest: /srv/teamengine/resources/lib
    remote_src: true
  with_items:
    - ets-wms11-{{ ets_wms11_version }}-site.jar

- name: download ets wms 1.1.1 data for qgis project
  get_url:
    url: http://opengeospatial.github.io/ets-wms11/data/data-wms-1.1.1.zip
    dest: /home/{{ user }}/data-wms-1.1.1.zip

- name: create data directory
  file:
    name: '/home/{{ user }}/data-wms-1.1.1'
    state: directory
  become: yes
  become_user: '{{ user }}'

- name: unarchive data
  unarchive:
    src: /home/{{ user }}/data-wms-1.1.1.zip
    dest: /home/{{ user }}/data-wms-1.1.1
    remote_src: true

# ----------------------------------------------------------------------------
# WMS 1.3.0
# ----------------------------------------------------------------------------
- name: clone testsuite for WMS-1.3.0
  git:
    repo: https://github.com/opengeospatial/ets-wms13
    dest: '/home/{{ user }}/ets-wms13'
    version: '{{ ets_wms13_version }}'
  become: yes
  become_user: '{{ user }}'
  register: pull_wms130

- name: build ets-wms13
  command: mvn install
  args:
    chdir: /home/{{ user }}/ets-wms13
  become: yes
  become_user: '{{ user }}'
  when: pull_wms130.changed

- name: install ets-wms13 scripts
  unarchive:
    src: /home/{{ user }}/ets-wms13/target/ets-wms13-{{ ets_wms13_version }}-ctl.zip
    dest: /srv/teamengine/scripts
    remote_src: true

- name: install ets-wms13 resources lib
  copy:
    src: /home/{{ user }}/ets-wms13/target/{{ item }}
    dest: /srv/teamengine/resources/lib
    remote_src: true
  with_items:
    - ets-wms13-{{ ets_wms13_version }}.jar
    - ets-wms13-{{ ets_wms13_version }}-site.jar

- name: download ets wms 1.3.0 data
  get_url:
    url: http://cite.opengeospatial.org/teamengine/about/wms/1.3.0/site/data-wms-1.3.0.zip
    dest: /home/{{ user }}/

- name: create data directory
  file:
    name: '/home/{{ user }}/data-wms-1.3.0'
    state: directory
  become: yes
  become_user: '{{ user }}'

- name: unarchive data
  unarchive:
    src: /home/{{ user }}/data-wms-1.3.0.zip
    dest: /home/{{ user }}/data-wms-1.3.0
    remote_src: true

- name: copy orignal getmap.xml file
  copy:
    remote_src: true
    src: /srv/teamengine/scripts/wms/1.3.0/ctl/getmap.xml
    dest: /srv/teamengine/scripts/wms/1.3.0/ctl/getmap_original.xml

- name: copy getmap.xml ctl script with failing tests deactivated
  copy:
    src: getmap.xml
    dest: /srv/teamengine/scripts/wms/1.3.0/ctl/getmap.xml

# ----------------------------------------------------------------------------
# WFS 2.0
# ----------------------------------------------------------------------------
- name: clone testsuite for WFS-2.0
  git:
    repo: https://github.com/opengeospatial/ets-wfs20
    dest: '/home/{{ user }}/ets-wfs20'
    version: '{{ ets_wfs20_version }}'
  become: yes
  become_user: '{{ user }}'
  register: pull_wfs20

- name: build ets-wfs20
  command: mvn install
  args:
    chdir: /home/{{ user }}/ets-wfs20
  become: yes
  become_user: '{{ user }}'
  when: pull_wfs20.changed

- name: install ets-wfs20 scripts
  unarchive:
    src: /home/{{ user }}/ets-wfs20/target/ets-wfs20-{{ ets_wfs20_version }}-ctl.zip
    dest: /srv/teamengine/scripts
    remote_src: true

- name: install ets-wfs20 resources lib
  unarchive:
    src: /home/{{ user }}/ets-wfs20/target/ets-wfs20-{{ ets_wfs20_version }}-deps.zip
    dest: /srv/teamengine/resources/lib
    remote_src: true

# ----------------------------------------------------------------------------
# WCS 2.0
# ----------------------------------------------------------------------------
- name: clone testsuite for WCS-2.0
  git:
    repo: https://github.com/opengeospatial/ets-wcs20
    dest: '/home/{{ user }}/ets-wcs20'
    version: '{{ ets_wcs20_version }}'
  become: yes
  become_user: '{{ user }}'
  register: pull_wcs20

- name: build ets-wcs20
  command: mvn install
  args:
    chdir: /home/{{ user }}/ets-wcs20
  become: yes
  become_user: '{{ user }}'
  when: pull_wcs20

- name: install ets-wcs20 scripts
  unarchive:
    src: /home/{{ user }}/ets-wcs20/target/ets-wcs20-{{ ets_wcs20_version }}-ctl.zip
    dest: /srv/teamengine/scripts
    remote_src: true

- name: install ets-wcs20 site jar
  copy:
    src: /home/{{ user }}/ets-wcs20/target/{{ item }}
    dest: /srv/teamengine/resources/lib
    remote_src: true
  with_items:
    - ets-wcs20-{{ ets_wcs20_version }}-site.jar

# ----------------------------------------------------------------------------
# WCS 1.0
# ----------------------------------------------------------------------------
- name: clone testsuite for WCS-1.0
  git:
    repo: https://github.com/opengeospatial/ets-wcs10
    dest: '/home/{{ user }}/ets-wcs10'
    version: '{{ ets_wcs10_version }}'
  become: yes
  become_user: '{{ user }}'
  register: pull_wcs10

- name: build ets-wcs10
  command: mvn install
  args:
    chdir: /home/{{ user }}/ets-wcs10
  become: yes
  become_user: '{{ user }}'
  when: pull_wcs10

- name: install ets-wcs10 scripts
  unarchive:
    src: /home/{{ user }}/ets-wcs10/target/ets-wcs10-{{ ets_wcs10_version }}-ctl.zip
    dest: /srv/teamengine/scripts
    remote_src: true

- name: install ets-wcs10 resources lib
  unarchive:
    src: /home/{{ user }}/ets-wcs10/target/{{ item }}
    dest: /srv/teamengine/resources/lib
    remote_src: true
  with_items:
    - ets-wcs10-{{ ets_wcs10_version }}-deps.zip

# ----------------------------------------------------------------------------
# WCS 1.1
# ----------------------------------------------------------------------------
- name: clone testsuite for WCS-1.1
  git:
    repo: https://github.com/opengeospatial/ets-wcs11
    dest: '/home/{{ user }}/ets-wcs11'
    version: '{{ ets_wcs11_version }}'
  become: yes
  become_user: '{{ user }}'
  register: pull_wcs11

- name: build ets-wcs11
  command: mvn install
  args:
    chdir: /home/{{ user }}/ets-wcs11
  become: yes
  become_user: '{{ user }}'
  when: pull_wcs11

- name: install ets-wcs11 scripts
  unarchive:
    src: /home/{{ user }}/ets-wcs11/target/ets-wcs11-{{ ets_wcs11_version }}-ctl.zip
    dest: /srv/teamengine/scripts
    remote_src: true

- name: install ets-wcs11 resources lib
  copy:
    src: /home/{{ user }}/ets-wcs11/target/{{ item }}
    dest: /srv/teamengine/resources/lib
    remote_src: true
  with_items:
    - ets-wcs11-{{ ets_wcs11_version }}.jar
    - ets-wcs11-{{ ets_wcs11_version }}-site.jar

# ----------------------------------------------------------------------------
# WFS 1.1.0
# ----------------------------------------------------------------------------
- name: clone testsuite for WFS-1.1
  git:
    repo: https://github.com/opengeospatial/ets-wfs11
    dest: '/home/{{ user }}/ets-wfs11'
    version: '{{ ets_wfs11_version }}'
  become: yes
  become_user: '{{ user }}'
  register: pull_wfs11

- name: build ets-wfs11
  command: mvn install
  args:
    chdir: /home/{{ user }}/ets-wfs11
  become: yes
  become_user: '{{ user }}'
  when: pull_wfs11

- name: install ets-wfs11 scripts
  unarchive:
    src: /home/{{ user }}/ets-wfs11/target/ets-wfs11-{{ ets_wfs11_version }}-ctl.zip
    dest: /srv/teamengine/scripts
    remote_src: true

- name: install ets-wfs11 resources lib
  unarchive:
    src: /home/{{ user }}/ets-wfs11/target/ets-wfs11-{{ ets_wfs11_version }}-deps.zip
    dest: /srv/teamengine/resources/lib
    remote_src: true

- name: download ets wfs 1.1.0 data for qgis project
  get_url:
    url: http://opengeospatial.github.io/ets-wfs11/data-wfs-1.1.0.zip
    dest: /home/{{ user }}/data-wfs-1.1.0.zip

- name: create data directory
  file:
    name: '/home/{{ user }}/data-wfs-1.1.0'
    state: directory
  become: yes
  become_user: '{{ user }}'

- name: unarchive data
  unarchive:
    src: /home/{{ user }}/data-wfs-1.1.0.zip
    dest: /home/{{ user }}/data-wfs-1.1.0
    remote_src: true

# ----------------------------------------------------------------------------
# WFS 1.0
# ----------------------------------------------------------------------------
- name: clone testsuite for WFS-1.0
  git:
    repo: https://github.com/opengeospatial/ets-wfs10
    dest: '/home/{{ user }}/ets-wfs10'
    version: '{{ ets_wfs10_version }}'
  become: yes
  become_user: '{{ user }}'
  register: pull_wfs10

- name: build ets-wfs10
  command: mvn install
  args:
    chdir: /home/{{ user }}/ets-wfs10
  become: yes
  become_user: '{{ user }}'
  when: pull_wfs10

- name: install ets-wfs10 scripts
  unarchive:
    src: /home/{{ user }}/ets-wfs10/target/ets-wfs10-{{ ets_wfs10_version }}-ctl.zip
    dest: /srv/teamengine/scripts
    remote_src: true

- name: install ets-wfs10 resources lib
  unarchive:
    src: /home/{{ user }}/ets-wfs10/target/ets-wfs10-{{ ets_wfs10_version }}-deps.zip
    dest: /srv/teamengine/resources/lib
    remote_src: true

# ----------------------------------------------------------------------------
# WMS SLD 1.1
# ----------------------------------------------------------------------------
- name: clone testsuite for WMS-SLD-1.1
  git:
    repo: https://github.com/opengeospatial/ets-wms-sld11
    dest: '/home/{{ user }}/ets-wms-sld11'
    version: '{{ ets_wmssld11_version }}'
  become: yes
  become_user: '{{ user }}'
  register: pull_wmssld11

  # - name: build ets-wms-sld11
  #   command: mvn install
  #   args:
  #     chdir: /home/{{ user }}/ets-wms-sld11
  #   become: yes
  #   become_user: '{{ user }}'
  #   when: pull_wmssld11
